### ISSUE TITLE
Training code release request！

### ISSUE THREAD

**Issue by yanty123** [ziqihuangg/ReVersion#1]
Hi ziqi, could you please release the training codes of your amazing work？

**Comment by sam-motamed** [comment]
I second this. Looking forward to it

**Comment by janekm** [comment]
Adding myself to this so I'll get a notification when it's released, hopefully 🤷‍♂️

**Comment by ziqihuangg** [comment]
Thanks for your interest! We'll most likely release the training code in Aug.

**Comment by qsunyuan** [comment]
+1

**Comment by ziqihuangg** [comment]
Hi! We've released the training code. Thanks for your patience.
