### ISSUE TITLE
About how to set the "initializer_token"

### ISSUE THREAD

**Issue by lxycopper** [ziqihuangg/ReVersion#7]
Nice work!

![1706083445248](https://github.com/ziqihuangg/ReVersion/assets/52530394/ba15968d-db37-4bc5-8c78-f2302b813db8)

I am curious about the initializer_token's setting. Why it uses "**and**" instead of those words more related to "painted_on", such as "paint" , "painted" or etc.

**Comment by ziqihuangg** [comment]
Hi, thanks for your question! Based on our experience, different initializations do not significantly impact the visual results of the final learned <R>. However, we haven't conducted systematic experiments on this matter yet, and you are welcome to explore it further.

**Comment by ziqihuangg** [comment]
Hi, I'm closing this issue as there's no follow-up question so far, but feel free to re-open it anytime if you got any questions at all!
