### ISSUE TITLE
more detail about figure3

### ISSUE THREAD

**Issue by CoMo6** [ziqihuangg/ReVersion#8]
Hi!
Thanks for your great job, can I have more detailed information about Figure 3?
Thanks.

**Comment by ziqihuangg** [comment]
Hi, thanks for your question! Are you referring to the Part-of-Speech Clustering Figure? It's a visualization of word distribution in CLIP’s text embedding space.

**Comment by ziqihuangg** [comment]
Hi, I'm closing this issue as there's no follow-up question so far, but feel free to re-open it anytime if you got any questions at all!
